name: Release Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create plugin zip
      run: |
        # Exclude .github, .gitignore, README.md, LICENSE from the zip
        zip -r wp-vanta.zip . -x ".github/*" ".gitignore" "README.md" "LICENSE"

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./wp-vanta.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
